name: Build
on: [push]
jobs:
  linux_arm:
    name: Linux ARM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: arm-unknown-linux-gnueabi
          override: true
      - run: apt update
      - run: apt install -y libdbus-1-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target arm-unknown-linux-gnueabi
      - run: ls target
